FROM datamart/devbase:0.1.0

RUN git clone https://github.com/fede1024/kafka-benchmark.git /kafka-benchmark
WORKDIR /kafka-benchmark

RUN cargo install

RUN sed -i.bak s/localhost:9092/kafka:9092/g producer_benchmark_config.yaml && cat producer_benchmark_config.yaml

RUN echo -n 'kafka-benchmark --config producer_benchmark_config.yaml --scenario msg_bursts_base' > start.sh && \
    chmod +x start.sh

CMD ["start.sh"]
