version: '3'
services:
  kafka:
    image: spotify/kafka
    hostname: kafka
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
    ports:
      - "9092:9092"
      - "2181:2181"
  itest:
    image: datamart/test
    depends_on:
      - kafka
    extra_hosts:
      - "kafka:162.242.195.82"
    # links:
    #   - kafka
    volumes:
      - .:/mount
    command: ["/bin/bash", "-c", "sleep 10; ./start.sh"]

