version: '3'
services:
  kafka:
    image: spotify/kafka
    hostname: kafka
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
      NUM_PARTITIONS: 3
      AUTO_CREATE_TOPICS: "true"
    ports:
      - "9092:9092"
      - "2181:2181"
  itest:
    image: datamart/test
    depends_on:
      - kafka
    volumes:
      - .:/mount
    command: ["/bin/bash", "-c", "sleep 10; ./start.sh"]

