version: '3'
services:
  kafka:
    image: spotify/kafka
    hostname: kafka
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
      NUM_PARTITIONS: 3
      AUTO_CREATE_TOPICS: "true"
    ports:
      - "9092:9092"
      - "2181:2181"
  demo:
    image: datamart/dev
    depends_on:
      - kafka
    volumes:
      - .:/mount
    command: ["data_mart_demo", "--brokers", "kafka:9092", "--input-topic",
              "test_topic", "--output-topic", "test_topic_out"]

